
FROM tiangolo/uvicorn-gunicorn-fastapi:python3.8

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/mini_assignment/

ARG ENVIRONMENT=test
RUN bash -c "if [ $ENVIRONMENT == "dev" ] || [ $ENVIRONMENT == "prod" ] ; then poetry install --no-root ; else poetry install --no-root --no-dev ; fi"

COPY . /usr/mini_assignment/


RUN chmod +x /usr/mini_assignment/start.sh

RUN chmod +x /usr/mini_assignment/test.sh
